package jogo.logica;

public enum Propriedades {
    ATUALIZAR_ESTADO,
    ATUALIZAR_TABULEIRO,
    ATUALIZAR_LISTA_JOGADORES,
    ATUALIZAR_JOGADOR_ATUAL,
    ATUALIZAR_PERGUNTA_MINIJOGO,
    ATUALIZAR_VENCEDOR
}
